### ISSUE TITLE
Net::EmptyPort::wait_port doesn't work as advertised

### ISSUE THREAD

**Issue by mauke** [tokuhirom/Test-TCP#12]
As far as I can tell, `Net::EmptyPort::wait_port` doesn't work as documented. The main logic is:

    while ( $retry-- ) {
        if ($^O eq 'MSWin32' ? `$^X -MTest::TCP::CheckPort -echeck_port $port $proto` : check_port( $port, $proto )) {
            return 1;
        }
        Time::HiRes::sleep($sleep);
    }
    return 0;

That is, it returns true if `check_port` returns true, and false if `check_port` returns false.

But the documentation for `check_port` says:

> Returns true if it is in use (i.e. if the port is NOT free).

... while the documentation for `wait_port` says:

> Return true if the port is available, false otherwise.

So which is correct? The code or the documentation?

(By the way, one of the Starman tests is failing for me because it seems to rely on `wait_port` working as documented, not as coded.)

**Comment by JJ** [comment]
Do you mean patches to the code or to the documentation? I've been asigned this by the CPAN pull request challenge and would like to know how can I help.

**Comment by kazuho** [comment]
In commit 88dfc16 the document has been updated as:
```
    "check_port(\%args)"
    "check_port($port)"
    "check_port($port, $proto)"
            my $true_or_false = check_port(5000);

        Checks if the given port is already in use. Returns true if it is in
        use (i.e. if the port is NOT free). Returns false if the port is
        free.
(snip)
    "wait_port(\%args)"
    "wait_port($port)"
    "wait_port($port, $max_wait)"
    "wait_port($port, $max_wait, $proto)"
        Waits until a particular port becomes ready to connect to. Returns
        true if the port becomes ready, or false if otherwise.
```

If it is still confusing or you find other issues in the documentation, please feel free to open a new PR or reopen the issue.
