### ISSUE TITLE
ExtUtils::MakeMaker version

### ISSUE THREAD

**Issue by jwittkoski** [tokuhirom/Test-TCP#29]
I noticed that the recent switch to EUMM requires version 6.64. Is there a specific need to use 6.64 or will earlier version(s) work correctly also?

**Comment by JJ** [comment]
Hard to say. Will have to check.

**Comment by charsbar** [comment]
EUMM 6.64 typically means it wants to use TEST_REQUIRES keyword for WriteMakefile().

See also https://metacpan.org/source/TOKUHIROM/Minilla-v2.3.0/lib/Minilla/ModuleMaker/ExtUtilsMakeMaker.pm#L39 (Minilla is what tokuhirom uses to release Test-TCP)

**Comment by miyagawa** [comment]
since EUMM can bootstrap itself, requiring a higher version should not cause any issues (if it does that's an issue with EUMM in general since you're stuck in a old toolchain).

**Comment by jwittkoski** [comment]
To be clear, this wasn't causing any problems. Originally I was asking because in one of my projects it was the only library dependency forcing EUMM to be a newer version than the one in core (5.16.x). I noticed commit 351942a7572d1194ff58e3a0f09425452931dc60 bumped the required EUMM version and I was just wondering if it was needed or a side effect of the change in build process.
