### ISSUE TITLE
Tests fail in Strawberry Perl 5.20.2 on Windows 7

### ISSUE THREAD

**Issue by maxwellhaydn** [tokuhirom/Test-TCP#37]
Tests fail in 64-bit Strawberry Perl 5.20.2 on Windows 7 Professional. Here is the build log generated by `cpanm --test-only Test::TCP`, run as administrator:

```
cpanm (App::cpanminus) 1.7027 on perl 5.020002 built for MSWin32-x64-multi-thread
Work directory is C:\Users\cgdadmin/.cpanm/work/1429212415.6136
You have make C:\Strawberry\c\bin\dmake.exe
You have LWP 6.13
Falling back to Archive::Tar 2.04
Searching Test::TCP on cpanmetadb ...
--> Working on Test::TCP
Fetching http://www.cpan.org/authors/id/K/KA/KAZUHO/Test-TCP-2.11.tar.gz
-> OK
Unpacking Test-TCP-2.11.tar.gz
Entering Test-TCP-2.11
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.64 ... Yes (7.04)
Configuring Test-TCP-2.11
Running Makefile.PL
cp META.json MYMETA.json
cp META.yml MYMETA.yml
Checking if your kit is complete...
Looks good
Generating a dmake-style Makefile
Writing Makefile for Test::TCP
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Time::HiRes 0 ... Yes (1.9726)
Checking if you have Socket 0 ... Yes (2.018)
Checking if you have Test::More 0.98 ... Yes (1.001014)
Checking if you have IO::Socket::INET 0 ... Yes (1.35)
Checking if you have File::Temp 0 ... Yes (0.2304)
Checking if you have Test::SharedFork 0.29 ... Yes (0.29)
Checking if you have IO::Socket::IP 0 ... Yes (0.36)
Building and testing Test-TCP-2.11
cp lib/Net/EmptyPort.pm blib\lib\Net\EmptyPort.pm
cp lib/Test/TCP/CheckPort.pm blib\lib\Test\TCP\CheckPort.pm
cp lib/Test/TCP.pm blib\lib\Test\TCP.pm
"C:\Strawberry\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib\lib', 'blib\arch')" t/*.t
# Test::More: 1.001014
t/00_compile.t ................. ok
cannot open port: ::1:51112 at C:\Users\cgdadmin\.cpanm\work\1429212415.6136\Test-TCP-2.11\blib\lib/Test/TCP.pm line 54.
    # Child (v6) exited without calling finalize()

#   Failed test 'v6'
#   at C:/Strawberry/perl/lib/Test/Builder.pm line 279.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 2.
t/01_simple.t .................. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/2 subtests 
t/02_abrt.t .................... skipped: win32 doesn't support embedded function named dump()
t/03_return_when_sigterm.t ..... ok
t/04_die.t ..................... ok
t/05_sigint.t .................. skipped: this test requires SIGUSR1
t/06_nest.t .................... ok
t/07_optional.t ................ ok
t/08_exit.t .................... ok
t/09_fork.t .................... ok
t/10_oo.t ...................... ok
    
    #   Failed test 'port is open'
    #   at t/11_net_empty_port.t line 22.
    # Looks like you failed 1 test of 4.

#   Failed test 'v6'
#   at t/11_net_empty_port.t line 37.
# Looks like you failed 1 test of 4.
t/11_net_empty_port.t .......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/4 subtests 
t/12_pass_wait_port_options.t .. ok
t/13_undef_port.t .............. ok

Test Summary Report
-------------------
t/01_simple.t                (Wstat: 65280 Tests: 2 Failed: 1)
  Failed test:  2
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/11_net_empty_port.t        (Wstat: 256 Tests: 4 Failed: 1)
  Failed test:  4
  Non-zero exit status: 1
Files=14, Tests=117, 87 wallclock secs ( 0.11 usr +  0.02 sys =  0.13 CPU)
Result: FAIL
Failed 2/14 test programs. 2/117 subtests failed.
dmake.exe:  Error code 255, while making 'test_dynamic'
-> FAIL Testing Test::TCP failed. See C:\Users\cgdadmin\.cpanm\work\1429212415.6136\build.log for details. Retry with --force to force install it.
```

Perl version details:

```
Summary of my perl5 (revision 5 version 20 subversion 2) configuration:
   
  Platform:
    osname=MSWin32, osvers=6.3, archname=MSWin32-x64-multi-thread
    uname='Win32 strawberry-perl 5.20.2.1 #1 Sat Feb 21 18:04:11 2015 x64'
    config_args='undef'
    hint=recommended, useposix=true, d_sigaction=undef
    useithreads=define, usemultiplicity=define
    use64bitint=define, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags =' -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE  -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLI
CIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields',
    optimize='-s -O2',
    cppflags='-DWIN32'
    ccversion='', gccversion='4.8.3', gccosandvers=''
    intsize=4, longsize=4, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long long', ivsize=8, nvtype='double', nvsize=8, Off_t='long long', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='g++.exe', ldflags ='-s -L"C:\strawberry\perl\lib\CORE" -L"C:\strawberry\c\lib"'
    libpth=C:\strawberry\c\lib C:\strawberry\c\x86_64-w64-mingw32\lib C:\strawberry\c\lib\gcc\x86_64
-w64-mingw32\4.8.3
    libs=-lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -
loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    perllibs=-lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole
32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    libc=, so=dll, useshrplib=true, libperl=libperl520.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs, dlext=xs.dll, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags='-mdll -s -L"C:\strawberry\perl\lib\CORE" -L"C:\strawberry\c\lib"'


Characteristics of this binary (from libperl): 
  Compile-time options: HAS_TIMES HAVE_INTERP_INTERN MULTIPLICITY
                        PERLIO_LAYERS PERL_DONT_CREATE_GVSV
                        PERL_HASH_FUNC_ONE_AT_A_TIME_HARD
                        PERL_IMPLICIT_CONTEXT PERL_IMPLICIT_SYS
                        PERL_MALLOC_WRAP PERL_NEW_COPY_ON_WRITE
                        PERL_PRESERVE_IVUV USE_64_BIT_INT USE_ITHREADS
                        USE_LARGE_FILES USE_LOCALE USE_LOCALE_COLLATE
                        USE_LOCALE_CTYPE USE_LOCALE_NUMERIC USE_PERLIO
                        USE_PERL_ATOF
  Built under MSWin32
  Compiled at Feb 21 2015 18:08:23
  %ENV:
    PERL_MM_USE_DEFAULT="0"
  @INC:
    C:/strawberry/perl/site/lib
    C:/strawberry/perl/vendor/lib
    C:/strawberry/perl/lib
    .
```

**Comment by clarkc2** [comment]
Same errors in Windows Server 2008 64-bit, Strawberry Perl 5.20.2:

<pre>
cpanm (App::cpanminus) 1.7027 on perl 5.020002 built for MSWin32-x64-multi-thread
Work directory is C:\Users\dbadmin/.cpanm/work/1432632296.9976
You have make C:\Strawberry\c\bin\dmake.exe
You have LWP 6.13
Falling back to Archive::Tar 2.04
You have C:\app\oracle\product\10.2.0\client_1\bin\unzip.exe
Searching Test::TCP on cpanmetadb ...
--> Working on Test::TCP
Fetching http://www.cpan.org/authors/id/T/TO/TOKUHIROM/Test-TCP-2.12.tar.gz
-> OK
Unpacking Test-TCP-2.12.tar.gz
Entering Test-TCP-2.12
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.04)
Configuring Test-TCP-2.12
Running Makefile.PL
Checking if your kit is complete...
Looks good
Generating a dmake-style Makefile
Writing Makefile for Test::TCP
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Time::HiRes 0 ... Yes (1.9726)
Checking if you have Test::More 0.98 ... Yes (1.001014)
Checking if you have IO::Socket::IP 0 ... Yes (0.36)
Checking if you have Test::SharedFork 0.29 ... Yes (0.31)
Checking if you have IO::Socket::INET 0 ... Yes (1.35)
Checking if you have Socket 0 ... Yes (2.018)
Checking if you have File::Temp 0 ... Yes (0.2304)
Building and testing Test-TCP-2.12
cp lib/Net/EmptyPort.pm blib\lib\Net\EmptyPort.pm
cp lib/Test/TCP.pm blib\lib\Test\TCP.pm
cp lib/Test/TCP/CheckPort.pm blib\lib\Test\TCP\CheckPort.pm
"C:\Strawberry\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib\lib', 'blib\arch')" t/*.t
# Test::More: 1.001014
t/00_compile.t ................. ok
cannot open port: ::1:50953 at C:\Users\dbadmin\.cpanm\work\1432632296.9976\Test-TCP-2.12\blib\lib/Test/TCP.pm line 54.
    # Child (v6) exited without calling finalize()

#   Failed test 'v6'
#   at C:/Strawberry/perl/lib/Test/Builder.pm line 279.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 2.
t/01_simple.t .................. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/2 subtests 
t/02_abrt.t .................... skipped: win32 doesn't support embedded function named dump()
t/03_return_when_sigterm.t ..... ok
t/04_die.t ..................... ok
t/05_sigint.t .................. skipped: this test requires SIGUSR1
t/06_nest.t .................... ok
t/07_optional.t ................ ok
t/08_exit.t .................... ok
t/09_fork.t .................... ok
t/10_oo.t ...................... ok
    
    #   Failed test 'port is open'
    #   at t/11_net_empty_port.t line 22.
    # Looks like you failed 1 test of 4.

#   Failed test 'v6'
#   at t/11_net_empty_port.t line 37.
# Looks like you failed 1 test of 4.
t/11_net_empty_port.t .......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/4 subtests 
t/12_pass_wait_port_options.t .. ok
t/13_undef_port.t .............. ok

Test Summary Report
-------------------
t/01_simple.t                (Wstat: 65280 Tests: 2 Failed: 1)
  Failed test:  2
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/11_net_empty_port.t        (Wstat: 256 Tests: 4 Failed: 1)
  Failed test:  4
  Non-zero exit status: 1
Files=14, Tests=117, 87 wallclock secs ( 0.09 usr +  0.03 sys =  0.13 CPU)
Result: FAIL
Failed 2/14 test programs. 2/117 subtests failed.
dmake.exe:  Error code 255, while making 'test_dynamic'
-> FAIL Testing Test::TCP failed. See C:\Users\dbadmin\.cpanm\work\1432632296.9976\build.log for details. Retry with --force to force install it.
</pre>

**Comment by wchristian** [comment]
Adressed in patch #42 and i think this can be closed.

**Comment by miyagawa** [comment]
Thanks!
