### ISSUE TITLE
[PATCH] fix a spelling mistake

### ISSUE THREAD

**Issue by gregoa** [tokuhirom/Test-TCP#38]
In Debian we are currently applying the following patch to Test-TCP.
We thought you might be interested in it too.

    Description: fix a spelling mistake
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2015-05-16
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libtest-tcp-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by tokuhirom** [comment]
Thanks!
