### ISSUE TITLE
"bind to an anvailable address" test fails

### ISSUE THREAD

**Issue by muraiki** [tokuhirom/Test-TCP#46]
I'm getting a test failure when installing Test::TCP. This is on Ubuntu 12.04.2 LTS with `perl 5, version 14, subversion 2 (v5.14.2) built for x86_64-linux-gnu-thread-multi`.

```
#   Failed test 'bind to an anvailable address'
#   at t/11_net_empty_port.t line 26.
# Looks like you failed 1 test of 4.
t/11_net_empty_port.t ..........
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/4 subtests
  (less 1 skipped subtest: 2 okay)
```

It looks like this test is trying to bind to an unavailable address and expecting to fail, but for some reason the bind is succeeding. I'm not sure why this is happening.

**Comment by muraiki** [comment]
I also tested it on a copy of perl-5.20.2 that I had installed via perlbrew; I got the same test failure.

**Comment by muraiki** [comment]
I tried installing on Ubuntu 14.04.3 LTS with perl-5.20.2 and it worked correctly. So perhaps it's a problem with 12.04.2?

**Comment by syohex** [comment]
Your fail test is here.

https://github.com/tokuhirom/Test-TCP/blob/597ed95d9c84a9b7c9c60edc726628f1795e6778/t/11_net_empty_port.t#L26

This test expects that you cannot bind `8.8.8.8`(Google Public DNS address). However you can bind `8.8.8.8` and on your environment and test is passed. So I suppose this is your environment issue(For example, you set `8.8.8.8` to your network interface etc).

**Comment by muraiki** [comment]
Yes, I'm just not sure why I'm able to bind to that address. My network interface is not set to 8.8.8.8.

I booted up a 12.04.2 virtual machine and could not reproduce the problem, so it is something in my environment.

The system that is failing is actually a virtual machine created by our systems team; other instances of that virtual machine also fail in the same way. I'll talk with them to see if they have something configured in such a way that would cause this test to fail. Thanks!

**Comment by kazuho** [comment]
One possibility is that your are running Linux, and have sysctl net.ipv4.ip_nonlocal_bind set to 1.

When set, the sysctl allows an application to bind to _any_ address, which is useful in some cases, for example when running a HA service using floating IP address.

Not sure if it is relevant to @muraiki's problem, but leaving a note so that others can be aware of the configuration variable.

**Comment by muraiki** [comment]
Thanks @kazuho -- that was the problem!
