### ISSUE TITLE
New maintainer required

### ISSUE THREAD

**Issue by tokuhirom** [tokuhirom/Test-TCP#56]
I want to retire to maintain this module. Can anyone maintain this module?

**Comment by miyagawa** [comment]
Seems @syohex is on it.

**Comment by nponeccop** [comment]
Do you still want to retire? I can maintain, NML@pause

**Comment by tokuhirom** [comment]
i added @nponeccop  as a collabolator

**Comment by nponeccop** [comment]
Can you publish it to CPAN or give me (`NML`) rights to do so. The current version fixes many issues

**Comment by miyagawa** [comment]
2.20 has been released to CPAN under my account.

**Comment by nponeccop** [comment]
Great! It's all green so far, including Windows! http://matrix.cpantesters.org/?dist=Test-TCP+2.20
