### ISSUE TITLE
Test-TCP 2.21: t/11_net_empty_port.t seems to fail on Windows 7 under Strawberry Perl 5.30.0

### ISSUE THREAD

**Issue by twata1** [tokuhirom/Test-TCP#82]
Hello,

It seemts to me that t/11_net_empty_port.t fails.
Please see the attached file.
[build-2.21.log](https://github.com/tokuhirom/Test-TCP/files/3694425/build-2.21.log)

[Environment]
Windows 7 32bit
Strawberry Perl 5.30.0

[My Workaround]
To install version 2.20.

**Comment by genehack** [comment]
Note that the same test fails on MacOS as well, but at a different spot:

```
t/11_net_empty_port.t .......... 1/?     # found an empty IPv6 port
t/11_net_empty_port.t .......... 13/?
    #   Failed test 'port is up'
    #   at t/11_net_empty_port.t line 94.
    # Looks like you failed 1 test of 2.

#   Failed test 'udp-wait-port'
#   at t/11_net_empty_port.t line 95.
# Looks like you failed 1 test of 16.
t/11_net_empty_port.t .......... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/16 subtests
```

**Comment by nponeccop** [comment]
It fails everywhere from Solaris to NetBSD:

- [FAIL Test-TCP-2.21 5.31.5 SunOS/Solaris]( http://www.cpantesters.org/cpan/report/44a373ea-e7dc-11e9-8866-eb9d52bc2478)
- [FAIL Test-TCP-2.21 5.26.3 NetBSD](http://www.cpantesters.org/cpan/report/a7acb7a8-e5c0-11e9-a65e-fe3acca03743)

See #84

**Comment by miyagawa** [comment]
I can reproduce on macOS and this patch seems to fix it: ```
diff --git a/t/11_net_empty_port.t b/t/11_net_empty_port.t
index 899fdbc..406b709 100644
--- a/t/11_net_empty_port.t
+++ b/t/11_net_empty_port.t
@@ -88,6 +88,7 @@ subtest 'udp-wait-port' => sub {
     ok !check_port($port, 'udp'), "port is down";
     my $sock = IO::Socket::IP->new(
         Proto     => 'udp',
+        LocalAddr => '127.0.0.1',
         LocalPort => $port,
         V6Only    => 1,
     ) or die "failed to bind to a UDP socket:$!";
```

can someone confirm if it works on other platforms like BSD too?

**Comment by genehack** [comment]
Confirming that @miyagawa's patch from above fixes the test on MacOS for me.

**Comment by twata1** [comment]
Thank you everyone!

I was able to confirm that Test-TCP 2.22 can be installed on Windows 7.
[build-2.22.log](https://github.com/tokuhirom/Test-TCP/files/3702318/build-2.22.log)
