### ISSUE TITLE
Test-TCP 2.21 is red on CPAN Testers compared to 2.20

### ISSUE THREAD

**Issue by nponeccop** [tokuhirom/Test-TCP#84]
It's not clear at the point whether there was a regression, but compare:

- http://matrix.cpantesters.org/?dist=Test-TCP%202.20 - almost all green
- http://matrix.cpantesters.org/?dist=Test-TCP%202.21 - almost all red except at Linux

**Comment by nponeccop** [comment]
#82 is apparently a regression, as 2.20 is listed as a workaround

**Comment by charsbar** [comment]
@nponeccop JFYI, CPANTS is not CPAN Testers. They are two different services.

**Comment by nponeccop** [comment]
@charsbar fixed

**Comment by charsbar** [comment]
@nponeccop thanks :)
